# Generated by Django 5.0.1 on 2024-01-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_like_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
